### ISSUE TITLE
Unable to access the CMS if no raygun key is set

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-raygun#24]
The Raygun Handler continues, even if there's no key set. The Raygun Vendor module then throws an error instead of gracefully cancelling the request.

https://github.com/silverstripe/silverstripe-raygun/blob/master/src/RaygunClientFactory.php#L38

**Comment by stojg** [comment]
The fix has been merged, so we should be able to close this issue?

**Comment by Firesphere** [comment]
Jeps, osrry.
