### ISSUE TITLE
'Only' block overrides all custom configuration

### ISSUE THREAD

**Issue by adrexia** [silverstripe/silverstripe-raygun#30]
From: https://github.com/silverstripe/silverstripe-raygun/commit/c46efb6174e421b9cc324d6430060fa7f7e32460#r27059407

```
Only:
  envorconstant: 'SS_RAYGUN_APP_KEY'
```

without a name means that modules that extend this one,  or project code, can not override any of the configuration provided in this module.

**Comment by micmania1** [comment]
PR?

**Comment by ichaber** [comment]
Greatly appreciate raising this issue @adrexia.
This issue should be resolved by release 3.0.0.
