### ISSUE TITLE
"Filter sensitive data" needs to be more paranoid

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-raygun#53]
Any env var with "token", "secret", "key", or "password" should be filtered out. Status quo it's likely to push a bunch of secrets stored in env vars for 3rd party services.

Losing an env var that isn't actually secret is benign and easily corrected on a per-site basis, sending data that we didn't want to is by far the biggest risk.

**Comment by robbieaverill** [comment]
Triaged as affecting SS4, since #54 fixed this for SS3

**Comment by chillu** [comment]
Follow up PR for 2.x and 3.x releases: https://github.com/silverstripe/silverstripe-raygun/pull/58
