### ISSUE TITLE
Update for Raygun PHP SDK v2 when it is released

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-raygun#59]
The PHP SDK is preparing for its v2 release, which includes some breaking changes (notably https://github.com/MindscapeHQ/raygun4php/pull/117 re: client instantiation).

Just a placeholder for now, but when it's tagged it'd be a good idea to update this module to either allow both versions to be installed, or release a new minor version with an updated upstream dependency.

**Comment by GuySartorelli** [comment]
v2.0.0 was released on Jan 28, 2020 and there have been two minor releases since then. Has there been any work towards updating this module to support the v2 sdk?

**Comment by brynwhyman** [comment]
Hey @GuySartorelli no work that I'm aware of. I wouldn't say that this module is active development by any stretch. 

I'd say there's an opportunity to become a maintainer if you're interested?

**Comment by GuySartorelli** [comment]
Good to know @brynwhyman 
We're still looking into our options as to which error reporting service we want to go with - I'll keep this in mind and if we do choose raygun I'll probably take you up on that.

**Comment by brynwhyman** [comment]
Hey @GuySartorelli, I'm personally open to following your lead on this, especially if you're also going to be the one to do the work! To your point, the third option is clearly the ideal, fingers crossed there might be some traction on that other pull request.

I've also just shared this issue around internally in the hopes that someone else might be able to help with maintainership/ supporting this contribution to the module.

**Comment by GuySartorelli** [comment]
Finally got around to submitting a PR for this 🎉

**Comment by madmatt** [comment]
Fantastic work, thank you!
