### ISSUE TITLE
Exclusion of sensitive data

### ISSUE THREAD

**Issue by siekanski** [silverstripe/silverstripe-raygun#61]
I have a problem. The main Raygun's documentation contains one magic sentence. "Note that when any filters are defined, the Raygun error will no longer contain the raw HTTP data, since there's no effective way to filter it.". In this situation, I wonder how I can encrypt selected sensitive data and transfer the necessary data from rawData? For each registered error I need to know what request flew to my api. However, encryption makes me not able to see it. Is there any way to do this?

**Comment by GuySartorelli** [comment]
I was about to link MindscapeHQ/raygun4php#136 and then realised this is actually literally the exact same issue.
Ultimately this belongs in the raygun4php issue tracker, not here - and there is advice in that issue for working around it.

I think this issue should be closed.

**Comment by madmatt** [comment]
Hi @siekanski, hopefully @GuySartorelli's comment makes sense to you - if not, please feel free to re-open this issue.

Thanks!
